### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by mach7** [thib3113/node-red-contrib-vban#4]
I'm getting this error when trying to use this node: (node:5033) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [VBANServer]. Use emitter.setMaxListeners() to increase limit

**Comment by thib3113** [comment]
Hello, 

This is just a warning, that telling that too much (for the configured leak detector) "nodes" listen to the VBAN server . 

I already disable it on my side, so I'm releasing a little update with it :) .

---

Released in the 1.2.5 . Can you confirm if its resolve the warning on your side ?
